### ISSUE TITLE
error: weak declaration of 'thrd_exit' must be public

### ISSUE THREAD

**Issue by satmandu** [jtsiomb/c11threads#19]
When building grep 3.8 I see this issue. (I've saved [c11threads.h](https://github.com/jtsiomb/c11threads/blob/master/c11threads.h) to `/usr/local/include/threads.h` on a i686 glibc 2.23 system.)

```
In file included from ./glthread/lock.h:87,
                 from glthread/lock.c:22:
/usr/local/include/threads.h:69:20: error: weak declaration of 'thrd_exit' must be public
   69 | static inline void thrd_exit(int res)
      |                    ^~~~~~~~~
make[3]: *** [Makefile:3661: glthread/libgreputils_a-lock.o] Error 1
```

**Comment by jtsiomb** [comment]
I don't know why that is. And I don't have the time currently to look into it. If you happen to dig deeper and find why thrd_exit must be public please let me know.

Maybe that implies that the implementation already has a notion of thrd_exit and this one conflicts with it? Did they finally add C11 threads to glibc after all those years and maybe this header is no longer necessary?

The design behind this project was to just drop a header file which provides the new functions as static inline, without adding a separate translation unit. So the fact that it's not a public symbol is by design. So I'm not sure what I'm supposed to do with that error, at least not without more information about it.

**Comment by satmandu** [comment]
Thanks for the feedback. We've just been using this file as a drop-in on older systems which don't have `threads.h`, but it turns out that just removing this file lets `grep` build just fine, so this issue probably isn't worth pursuing further.
