### ISSUE TITLE
<stdint.h>

### ISSUE THREAD

**Issue by vinipsmaker** [jtsiomb/c11threads#2]
Why aren't you using `<stdint.h>` when makes sense?

A few places where it would make sense are:
- [c11threads:39](https://github.com/jtsiomb/c11threads/blob/62cc515e22ad1418e3ae767a2d43fcd85f8e0b12/c11threads.h#L39).
- `intptr_t` at [c11threads.h:69](https://github.com/jtsiomb/c11threads/blob/62cc515e22ad1418e3ae767a2d43fcd85f8e0b12/c11threads.h#L69).

**Comment by jtsiomb** [comment]
On Thu, Jul 02, 2015 at 07:32:16AM -0700, Vinícius dos Santos Oliveira wrote:

> Why aren't you using `<stdint.h>` when makes sense?
> 
> A few places where it would make sense are:
> - [c11threads:39](https://github.com/jtsiomb/c11threads/blob/62cc515e22ad1418e3ae767a2d43fcd85f8e0b12/c11threads.h#L39).
> - `intptr_t` at [c11threads.h:69](https://github.com/jtsiomb/c11threads/blob/62cc515e22ad1418e3ae767a2d43fcd85f8e0b12/c11threads.h#L69).

I can't find the standard at the moment, but I think that's how the
xtime structure was defined. I was working from a draft of the C11
standard actually, so I don't know if things have changed afterwards.
Somebody told me they completely removed the xtime structure in the
final version, but I never revisited this to update it.

In the second instance, I don't see what would be gained by casting to
intptr_t instead of long to justify including another header file just
for that.

## 

John Tsiombikas
http://nuclear.mutantstargoat.com/

**Comment by vinipsmaker** [comment]
> In the second instance, I don't see what would be gained by casting to intptr_t instead of long to justify including another header file just for that.

Better support for multiple architectures?

And I've only looked at the beginning of the implementation file. I believe more examples could be found if I continued to read the code (which is not that large).

**Comment by jtsiomb** [comment]
I'm sorry I don't see how your proposed change would help support more architectures than the existing code. If you find any actual problems after looking at the rest of the code, feel free to reopen this issue, preferably followed by a pull request or diff of changes, to fix any such issues.
